# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-adapter-http
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: adapter-http
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: adapter-http
    spec:
      containers:
        - env:
            - name: MF_JAEGER_URL
              value: {{ .Release.Name }}-jaeger-operator-jaeger-agent:{{ .Values.defaults.jaegerPort }}
            - name: MF_HTTP_ADAPTER_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.adapter_http.logLevel }}
            - name: MF_HTTP_ADAPTER_PORT
              value: "{{ .Values.adapter_http.httpPort }}"
            - name: MF_NATS_URL
              value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
            - name: MF_RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:{{ .Values.defaults.rabbitmqPort }}
            - name: MF_RABBITMQ_TLS_CONFIG
              value: {{ .Values.rabbitmq.tlsConfig }}
            - name: MF_RABBITMQ_DURABLE
              value: {{ .Values.rabbitmq.durable }}
            - name: MF_RABBITMQ_TTL
              value: {{ .Values.rabbitmq.ttl }}
            - name: MF_RABBITMQ_PRIORITY
              value: {{ .Values.rabbitmq.priority }}
            - name: MF_RABBITMQ_CONTENT_TYPE
              value: {{ .Values.rabbitmq.contentType }}
            - name: MF_RABBITMQ_SUB_SYSTEM
              value: {{ .Values.rabbitmq.subSystem }}
            - name: MF_RABBITMQ_SEVERITY
              value: {{ .Values.rabbitmq.severity }}
            - name: MF_RABBITMQ_QUEUE
              value: {{ .Values.rabbitmq.queue }}
            - name: MF_THINGS_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.things.authGrpcPort }}
          image: "{{ default .Values.defaults.image.repository .Values.adapter_http.image.repository }}/http:{{ default .Values.defaults.image.tag .Values.adapter_http.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.adapter_http.image.pullPolicy }}
          name: {{ .Release.Name }}-adapter-http
          ports:
            - containerPort: {{ .Values.adapter_http.httpPort }}
              protocol: TCP
          stdin: true
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
