# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-adapter-coap
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: adapter-coap
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: adapter-coap
    spec:
      containers:
        - env:
            - name: MF_JAEGER_URL
              value: {{ .Release.Name }}-jaeger-operator-jaeger-agent:{{ .Values.defaults.jaegerPort }}
            - name: MF_NATS_URL
              value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
            - name: MF_RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:{{ .Values.defaults.rabbitmqPort }}
            - name: MF_RABBITMQ_TLS_CONFIG
              value: {{ .Values.rabbitmq.tlsConfig }}
            - name: MF_RABBITMQ_DURABLE
              value: {{ .Values.rabbitmq.durable }}
            - name: MF_RABBITMQ_TTL
              value: {{ .Values.rabbitmq.ttl }}
            - name: MF_RABBITMQ_PRIORITY
              value: {{ .Values.rabbitmq.priority }}
            - name: MF_RABBITMQ_CONTENT_TYPE
              value: {{ .Values.rabbitmq.contentType }}
            - name: MF_RABBITMQ_SUB_SYSTEM
              value: {{ .Values.rabbitmq.subSystem }}
            - name: MF_RABBITMQ_SEVERITY
              value: {{ .Values.rabbitmq.severity }}
            - name: MF_RABBITMQ_QUEUE
              value: {{ .Values.rabbitmq.queue }}
            - name: MF_THINGS_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.things.authGrpcPort }}
            - name: MF_COAP_ADAPTER_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.adapter_coap.logLevel }}
            - name: MF_COAP_ADAPTER_PORT
              value: "{{ .Values.adapter_coap.udpPort }}"
          image: "{{ default .Values.defaults.image.repository .Values.adapter_coap.image.repository }}/coap:{{ default .Values.defaults.image.tag .Values.adapter_coap.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.adapter_coap.image.pullPolicy }}
          name: {{ .Release.Name }}-adapter-coap
          ports:
            - containerPort: {{ .Values.adapter_coap.udpPort }}
              protocol: UDP
          stdin: true
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
